# Generated by Django 5.0.2 on 2024-03-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_club_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
