# Generated by Django 5.0.2 on 2024-04-09 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_alter_club_image'),
        ('clubs', '0009_rename_follows_follow'),
    ]

    operations = [
    ]
