# Generated by Django 5.0.2 on 2024-04-09 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_merge_20240407_1305'),
        ('clubs', '0010_merge_20240409_1355'),
    ]

    operations = [
    ]
