# Generated by Django 5.0.2 on 2024-04-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0011_merge_20240409_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='image',
            field=models.ImageField(default='/clubs/CampusConnectLogo.svg', upload_to='clubs'),
        ),
    ]
