# Generated by Django 5.0.2 on 2024-04-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0013_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='contact',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
