# Generated by Django 5.0.2 on 2024-04-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='prof/default-pfp.png', null=True, upload_to='prof'),
        ),
    ]
