# Generated by Django 5.0.2 on 2024-04-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='prof/default-pfp.jpg', null=True, upload_to='prof'),
        ),
    ]
