# Generated by Django 5.0.2 on 2024-04-29 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_eventreact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='title',
        ),
    ]
