# Generated by Django 5.0.2 on 2024-04-24 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_comment_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="posts.comment",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="images"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="summary",
            field=models.TextField(default="No Summary", max_length=255),
        ),
    ]
