# Generated by Django 5.0.2 on 2024-03-27 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_alter_club_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='image',
        ),
    ]
