# Generated by Django 5.0.2 on 2024-04-03 23:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0008_club_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="image",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="clubs"
            ),
            preserve_default=False,
        ),
    ]
