# Generated by Django 5.0.2 on 2024-04-04 02:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_club_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follows',
            new_name='Follow',
        ),
    ]
