# Generated by Django 5.0.2 on 2024-04-10 06:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0011_merge_20240409_1430'),
        ('event', '0002_rename_date_event_event_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='user',
            new_name='author',
        ),
        migrations.AddField(
            model_name='event',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clubs.club'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='time_posted',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
