# Generated by Django 5.0.2 on 2024-04-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_eventattending'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventattending',
            name='attending',
            field=models.BooleanField(default=False),
        ),
    ]
